### ISSUE TITLE
YAML: Variable resolution incorrect

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/testsuite-nocoding#12]
When your yaml file define "host" and you access it later with ${host}, the data should not be taken from the properties but from the data in the yaml file. Only if you do not define host in the yaml file, you should take it from the properties.

```
- Store :
    - host: "https://dev01.foo.net"
    
- Action :
    Name : AccountPage
    Request :
        Url : ${host}/account
```

Properties define host = http://localhost:8080

**Comment by matthiasware** [comment]
Done
