### ISSUE TITLE
Automatically identify the YAML/CSV file

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/testsuite-nocoding#15]
Add a feature that automatically falls back to a default YAML or CSV file name so that it does not have to be specified. Suggested is a lowercased version of the class name without the package. 

Additionally we could use an annotation at the test case or test method to set the name.

**Comment by jowerner** [comment]
If an explicit class-to-script mapping is not specified, the code will now try to find a matching script file based on the simple name of the Java test case class.

Example: For a test class `tests.TBrowse`, the code would look for the following script files, in this order:

* `<script-dir>/TBrowse.yml`
* `<script-dir>/TBrowse.yaml`
* `<script-dir>/TBrowse.csv`

The first script file found will be used.

**Comment by ckeiner** [comment]
Xlt-Nocoding automatically checks the classpath and the configured (or default) source directory for files with the exact same name as the class, including capitalization. In addition, it adds all extension the [ParserFactory](https://github.com/Xceptance/xlt-nocoding/blob/68acbf7bd71065e28e8d47f30c838b946f603cde/src/main/java/com/xceptance/xlt/nocoding/parser/ParserFactory.java) knows to the classname and searches for an existing file, which then gets parsed.
The priority of files is as follows:
 * Classpath > configured (or default) source directory
 * CSV types > YAML types
