### ISSUE TITLE
Actions and validations are incorrectly positioned

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/testsuite-nocoding#16]
Validation errors are not reported as failing actions, hence the validation takes place outside the action context. This might also be a problem for loading static content and XHR that is potentially not loaded as part of the action.

**Comment by ckeiner** [comment]
Previously if a validation fails, it is reported as follows:
![image](https://user-images.githubusercontent.com/27275355/53336522-d94c0f80-38fe-11e9-855e-f5e976c27694.png)
In [commit 0de2166552a242c01ae4f198ac0e57bd04a9be82](https://github.com/Xceptance/xlt-nocoding/tree/0de2166552a242c01ae4f198ac0e57bd04a9be82), information about the failed action is also added as follows:
![image](https://user-images.githubusercontent.com/27275355/53337615-2da4be80-3902-11e9-81d3-6be7ebb2884f.png)

The stack trace also shows that the validation happens inside an action.
If this doesn't solve your issue, please reopen it.
