### ISSUE TITLE
Scripts files should be parsed only once

### ISSUE THREAD

**Issue by jowerner** [Xceptance/testsuite-nocoding#19]
Currently, script files are parsed when the corresponding test case class is executed. During a load test, the script files would be parsed again and again, causing unnecessary overhead. The parsed scripts should be stored internally and reused for subsequent iterations.

**Comment by h-arlt** [comment]
Enhanced class `com.xceptance.xlt.common.util.action.data.URLActionDataListBuilder` to cache the parsed data internally.

Access to cache is done by the new method `getOrParseData()` that calls the newly introduced abstract method `parseData()` to load the data from the associated script file in case of a cache miss.

Both sub-classes have been adjusted to implement the method `parseData()` and to call `getOrParseData()` in `buildActionDataList()`.
