### ISSUE TITLE
Improve error message by adding CSV positions

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/testsuite-nocoding#3]
When requests fail, the CSV position is not properly reported.

**Comment by ckeiner** [comment]
The CSVParser of [commit d76549201c2a0f0fb1f268cd4d28b370497eebd7](https://github.com/Xceptance/xlt-nocoding/commit/d76549201c2a0f0fb1f268cd4d28b370497eebd7) adds the correct line number to any error message.
